version: "3.4"

services:
  database:
    image: "postgres:latest"
    container_name: fsbarber
    ports:
      - 5432:5432
    environment:
      POSGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
